-- ============================================================
-- Nhà Hàng Gánh Kèo — schema Supabase
-- Đồng bộ 1-1 với index.html (frontend giữ nguyên, không sửa).
-- Chạy được nhiều lần: Supabase Dashboard → SQL Editor → Run.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Bảng
-- ------------------------------------------------------------
create table if not exists public.bookings (
  id text primary key,
  name text not null,
  phone text not null,
  guests integer not null default 1 check (guests > 0),
  date date not null,
  time text not null,
  table_ids text[] not null default '{}',
  deposit numeric(12, 2) not null default 0 check (deposit >= 0),
  note text not null default '',
  status text not null default 'confirmed',
  check_in timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created timestamptz not null default now(),
  constraint bookings_status_check
    check (status in ('confirmed', 'arrived', 'completed', 'cancelled'))
);

create index if not exists bookings_date_time_idx
  on public.bookings (date, time);

create table if not exists public.walk_ins (
  id text primary key,
  customer_name text not null default '',
  date date not null,
  time text not null,
  table_ids text[] not null default '{}',
  guests integer not null check (guests > 0),
  status text not null default 'arrived',
  check_in timestamptz not null default now(),
  completed_at timestamptz,
  staff_name text not null,
  constraint walk_ins_status_check
    check (status in ('arrived', 'completed', 'cancelled'))
);

create index if not exists walk_ins_date_time_idx
  on public.walk_ins (date, time);

create table if not exists public.booking_history (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  staff_name text not null,
  action text not null,
  subject text not null
);

create table if not exists public.table_groups (
  id uuid primary key default gen_random_uuid(),
  table_ids text[] not null,
  created_at timestamptz not null default now(),
  check (cardinality(table_ids) >= 2)
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('manager', 'employee')),
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 2. Đồng bộ bảng đã tồn tại (chạy cho database đang dùng)
-- ------------------------------------------------------------

-- 2.1 Cột dùng bởi index.html
alter table public.walk_ins
  add column if not exists customer_name text not null default '';

-- 2.2 Trạng thái booking
-- Giao diện chỉ tạo/đọc 4 trạng thái: confirmed, arrived, completed, cancelled
-- (statusNames trong index.html). Dữ liệu cũ 'deposit' / 'hold' / 'no-show'
-- được quy về 4 giá trị này trước khi áp ràng buộc mới.
update public.bookings
  set status = case status
                 when 'deposit' then 'confirmed'
                 when 'hold'    then 'confirmed'
                 when 'no-show' then 'cancelled'
                 else 'confirmed'
               end
  where status not in ('confirmed', 'arrived', 'completed', 'cancelled');

update public.bookings
  set cancelled_at = coalesce(cancelled_at, now())
  where status = 'cancelled' and cancelled_at is null;

alter table public.bookings drop constraint if exists bookings_status_check;
alter table public.bookings add constraint bookings_status_check
  check (status in ('confirmed', 'arrived', 'completed', 'cancelled'));
alter table public.bookings alter column status set default 'confirmed';

-- 2.3 Trạng thái khách lẻ
-- Khách lẻ có thể đang phục vụ, hoàn tất hoặc bị hủy.
update public.walk_ins
  set status = case when status in ('completed', 'cancelled') then status else 'arrived' end
  where status not in ('arrived', 'completed', 'cancelled');

update public.walk_ins
  set completed_at = coalesce(completed_at, now())
  where status in ('completed', 'cancelled') and completed_at is null;

alter table public.walk_ins drop constraint if exists walk_ins_status_check;
alter table public.walk_ins add constraint walk_ins_status_check
  check (status in ('arrived', 'completed', 'cancelled'));
alter table public.walk_ins alter column status set default 'arrived';

-- ------------------------------------------------------------
-- 3. Phân quyền theo vai trò
-- ------------------------------------------------------------
create or replace function public.is_manager()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'manager'
  );
$$;

revoke all on function public.is_manager() from public, anon;
grant execute on function public.is_manager() to authenticated;

alter table public.bookings enable row level security;
alter table public.walk_ins enable row level security;
alter table public.booking_history enable row level security;
alter table public.table_groups enable row level security;
alter table public.user_roles enable row level security;

-- ------------------------------------------------------------
-- 4. RLS policy
-- Mọi tài khoản đã đăng nhập: đọc + tạo + cập nhật.
-- Chỉ manager: xoá (khớp với việc index.html ẩn mọi nút xoá khi không phải manager).
-- ------------------------------------------------------------
drop policy if exists "Authenticated users can manage bookings" on public.bookings;
drop policy if exists "Authenticated users can read bookings" on public.bookings;
drop policy if exists "Authenticated users can insert bookings" on public.bookings;
drop policy if exists "Authenticated users can update bookings" on public.bookings;
drop policy if exists "Managers can delete bookings" on public.bookings;
create policy "Authenticated users can read bookings"
  on public.bookings for select to authenticated using (true);
create policy "Authenticated users can insert bookings"
  on public.bookings for insert to authenticated with check (true);
create policy "Authenticated users can update bookings"
  on public.bookings for update to authenticated using (true) with check (true);
create policy "Managers can delete bookings"
  on public.bookings for delete to authenticated
  using (public.is_manager());

drop policy if exists "Authenticated users can manage walk-ins" on public.walk_ins;
drop policy if exists "Authenticated users can read walk-ins" on public.walk_ins;
drop policy if exists "Authenticated users can insert walk-ins" on public.walk_ins;
drop policy if exists "Authenticated users can update walk-ins" on public.walk_ins;
drop policy if exists "Managers can delete walk-ins" on public.walk_ins;
create policy "Authenticated users can read walk-ins"
  on public.walk_ins for select to authenticated using (true);
create policy "Authenticated users can insert walk-ins"
  on public.walk_ins for insert to authenticated with check (true);
create policy "Authenticated users can update walk-ins"
  on public.walk_ins for update to authenticated using (true) with check (true);
create policy "Managers can delete walk-ins"
  on public.walk_ins for delete to authenticated
  using (public.is_manager());

drop policy if exists "Authenticated users can manage booking history" on public.booking_history;
drop policy if exists "Authenticated users can read booking history" on public.booking_history;
drop policy if exists "Authenticated users can insert booking history" on public.booking_history;
drop policy if exists "Managers can delete booking history" on public.booking_history;
create policy "Authenticated users can read booking history"
  on public.booking_history for select to authenticated using (true);
create policy "Authenticated users can insert booking history"
  on public.booking_history for insert to authenticated with check (true);
create policy "Managers can delete booking history"
  on public.booking_history for delete to authenticated
  using (public.is_manager());

drop policy if exists "Authenticated users can manage table groups" on public.table_groups;
drop policy if exists "Authenticated users can read table groups" on public.table_groups;
drop policy if exists "Authenticated users can insert table groups" on public.table_groups;
drop policy if exists "Authenticated users can update table groups" on public.table_groups;
drop policy if exists "Managers can delete table groups" on public.table_groups;
create policy "Authenticated users can read table groups"
  on public.table_groups for select to authenticated using (true);
create policy "Authenticated users can insert table groups"
  on public.table_groups for insert to authenticated with check (true);
create policy "Authenticated users can update table groups"
  on public.table_groups for update to authenticated using (true) with check (true);
create policy "Managers can delete table groups"
  on public.table_groups for delete to authenticated
  using (public.is_manager());

drop policy if exists "Users can read their own role" on public.user_roles;
create policy "Users can read their own role"
  on public.user_roles for select to authenticated
  using (user_id = auth.uid() or public.is_manager());

-- ------------------------------------------------------------
-- 5. Quyền ở mức bảng
-- booking_history không có update: index.html chỉ đọc, thêm và xoá.
-- ------------------------------------------------------------
grant select, insert, update, delete
  on public.bookings, public.walk_ins, public.table_groups
  to authenticated;
grant select, insert, delete on public.booking_history to authenticated;
grant select on public.user_roles to authenticated;
grant usage, select on sequence public.booking_history_id_seq to authenticated;

revoke update on public.booking_history from authenticated;
-- ------------------------------------------------------------
-- 6. Kiểm tra sau khi chạy (xem kết quả ở tab kết quả của SQL Editor)
-- ------------------------------------------------------------

-- 6.1 Ràng buộc còn lại trên 2 bảng booking / khách lẻ
select conrelid::regclass::text as bang,
       conname as rang_buoc,
       pg_get_constraintdef(oid) as dinh_nghia
from pg_constraint
where conrelid in ('public.bookings'::regclass, 'public.walk_ins'::regclass)
  and contype = 'c'
order by 1, 2;

-- 6.2 Không còn trạng thái lạ ngoài 4 giá trị giao diện dùng
select 'bookings' as bang, status, count(*) as so_dong
from public.bookings
group by status
union all
select 'walk_ins', status, count(*)
from public.walk_ins
group by status
order by 1, 2;
