create table if not exists public.bookings (
  id text primary key,
  name text not null,
  phone text not null,
  guests integer not null default 1 check (guests > 0),
  date date not null,
  time text not null,
  table_ids text[] not null default '{}',
  deposit numeric(12, 2) not null default 0 check (deposit >= 0),
  note text not null default '',
  status text not null default 'confirmed'
    check (status in ('confirmed', 'deposit', 'arrived', 'completed', 'cancelled', 'hold', 'no-show')),
  check_in timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created timestamptz not null default now()
);

create index if not exists bookings_date_time_idx
  on public.bookings (date, time);

create table if not exists public.booking_history (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  staff_name text not null,
  action text not null,
  subject text not null
);

create table if not exists public.table_groups (
  id uuid primary key default gen_random_uuid(),
  table_ids text[] not null,
  created_at timestamptz not null default now(),
  check (cardinality(table_ids) >= 2)
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('manager', 'employee')),
  created_at timestamptz not null default now()
);

create or replace function public.is_manager()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'manager'
  );
$$;

revoke all on function public.is_manager() from public, anon;
grant execute on function public.is_manager() to authenticated;

alter table public.bookings enable row level security;
alter table public.booking_history enable row level security;
alter table public.table_groups enable row level security;
alter table public.user_roles enable row level security;

drop policy if exists "Authenticated users can manage bookings" on public.bookings;
drop policy if exists "Authenticated users can read bookings" on public.bookings;
drop policy if exists "Authenticated users can insert bookings" on public.bookings;
drop policy if exists "Authenticated users can update bookings" on public.bookings;
drop policy if exists "Managers can delete bookings" on public.bookings;
create policy "Authenticated users can read bookings"
  on public.bookings for select to authenticated using (true);
create policy "Authenticated users can insert bookings"
  on public.bookings for insert to authenticated with check (true);
create policy "Authenticated users can update bookings"
  on public.bookings for update to authenticated using (true) with check (true);
create policy "Managers can delete bookings"
  on public.bookings for delete to authenticated
  using (public.is_manager());

drop policy if exists "Authenticated users can manage booking history" on public.booking_history;
drop policy if exists "Authenticated users can read booking history" on public.booking_history;
drop policy if exists "Authenticated users can insert booking history" on public.booking_history;
drop policy if exists "Managers can delete booking history" on public.booking_history;
create policy "Authenticated users can read booking history"
  on public.booking_history for select to authenticated using (true);
create policy "Authenticated users can insert booking history"
  on public.booking_history for insert to authenticated with check (true);
create policy "Managers can delete booking history"
  on public.booking_history for delete to authenticated
  using (public.is_manager());

drop policy if exists "Authenticated users can manage table groups" on public.table_groups;
drop policy if exists "Authenticated users can read table groups" on public.table_groups;
drop policy if exists "Authenticated users can insert table groups" on public.table_groups;
drop policy if exists "Authenticated users can update table groups" on public.table_groups;
drop policy if exists "Managers can delete table groups" on public.table_groups;
create policy "Authenticated users can read table groups"
  on public.table_groups for select to authenticated using (true);
create policy "Authenticated users can insert table groups"
  on public.table_groups for insert to authenticated with check (true);
create policy "Authenticated users can update table groups"
  on public.table_groups for update to authenticated using (true) with check (true);
create policy "Managers can delete table groups"
  on public.table_groups for delete to authenticated
  using (public.is_manager());

drop policy if exists "Users can read their own role" on public.user_roles;
create policy "Users can read their own role"
  on public.user_roles for select to authenticated
  using (user_id = auth.uid() or public.is_manager());

grant select, insert, update, delete
  on public.bookings, public.table_groups
  to authenticated;
grant select, insert, delete on public.booking_history to authenticated;
grant select on public.user_roles to authenticated;
grant usage, select on sequence public.booking_history_id_seq to authenticated;

revoke update on public.booking_history from authenticated;
